// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace Data.Context.Configurations
{
    public partial class AccionesConfiguration : IEntityTypeConfiguration<Acciones>
    {
        public void Configure(EntityTypeBuilder<Acciones> entity)
        {
            entity.HasKey(e => e.IdAccion)
                .HasName("PK__Acciones__387C45617686F3AF");

            entity.Property(e => e.IdAccion).HasColumnName("id_accion");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Acciones> entity);
    }
}
