// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace Data.Context.Configurations
{
    public partial class AccionxRolConfiguration : IEntityTypeConfiguration<AccionxRol>
    {
        public void Configure(EntityTypeBuilder<AccionxRol> entity)
        {
            entity.HasKey(e => new { e.IdAccion, e.IdRol })
                .HasName("PK__AccionxR__2ED78E3F9F453107");

            entity.Property(e => e.IdAccion).HasColumnName("id_accion");

            entity.Property(e => e.IdRol).HasColumnName("id_rol");

            entity.HasOne(d => d.IdAccionNavigation)
                .WithMany(p => p.AccionxRol)
                .HasForeignKey(d => d.IdAccion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AccionxRo__id_ac__403A8C7D");

            entity.HasOne(d => d.IdRolNavigation)
                .WithMany(p => p.AccionxRol)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AccionxRo__id_ro__412EB0B6");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AccionxRol> entity);
    }
}
