// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace Data.Context.Configurations
{
    public partial class BeneficioxProductoConfiguration : IEntityTypeConfiguration<BeneficioxProducto>
    {
        public void Configure(EntityTypeBuilder<BeneficioxProducto> entity)
        {
            entity.HasKey(e => new { e.IdBeneficio, e.IdProducto })
                .HasName("PK__Benefici__27CF49F185EEFE85");

            entity.Property(e => e.IdBeneficio).HasColumnName("id_beneficio");

            entity.Property(e => e.IdProducto).HasColumnName("id_producto");

            entity.HasOne(d => d.IdBeneficioNavigation)
                .WithMany(p => p.BeneficioxProducto)
                .HasForeignKey(d => d.IdBeneficio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Beneficio__id_be__6383C8BA");

            entity.HasOne(d => d.IdProductoNavigation)
                .WithMany(p => p.BeneficioxProducto)
                .HasForeignKey(d => d.IdProducto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Beneficio__id_pr__6477ECF3");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BeneficioxProducto> entity);
    }
}
