// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace Data.Context.Configurations
{
    public partial class LineaDeVentaConfiguration : IEntityTypeConfiguration<LineaDeVenta>
    {
        public void Configure(EntityTypeBuilder<LineaDeVenta> entity)
        {
            entity.HasKey(e => new { e.IdVenta, e.IdProducto })
                .HasName("PK__LineaDeV__8A66727F7E90ACB7");

            entity.Property(e => e.IdVenta).HasColumnName("id_venta");

            entity.Property(e => e.IdProducto).HasColumnName("id_producto");

            entity.Property(e => e.Cantidad).HasColumnName("cantidad");

            entity.Property(e => e.PrecioActual)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio_actual");

            entity.HasOne(d => d.IdProductoNavigation)
                .WithMany(p => p.LineaDeVenta)
                .HasForeignKey(d => d.IdProducto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LineaDeVe__id_pr__5441852A");

            entity.HasOne(d => d.IdVentaNavigation)
                .WithMany(p => p.LineaDeVenta)
                .HasForeignKey(d => d.IdVenta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LineaDeVe__id_ve__534D60F1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LineaDeVenta> entity);
    }
}
