// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace Data.Context.Configurations
{
    public partial class RolxUsuarioConfiguration : IEntityTypeConfiguration<RolxUsuario>
    {
        public void Configure(EntityTypeBuilder<RolxUsuario> entity)
        {
            entity.HasKey(e => new { e.IdUsuario, e.IdRol })
                .HasName("PK__RolxUsua__5895CFF3F7C960ED");

            entity.Property(e => e.IdUsuario).HasColumnName("id_usuario");

            entity.Property(e => e.IdRol).HasColumnName("id_rol");

            entity.HasOne(d => d.IdRolNavigation)
                .WithMany(p => p.RolxUsuario)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RolxUsuar__id_ro__3B75D760");

            entity.HasOne(d => d.IdUsuarioNavigation)
                .WithMany(p => p.RolxUsuario)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RolxUsuar__id_us__3A81B327");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RolxUsuario> entity);
    }
}
