// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace Data.Context.Configurations
{
    public partial class StockConfiguration : IEntityTypeConfiguration<Stock>
    {
        public void Configure(EntityTypeBuilder<Stock> entity)
        {
            entity.HasKey(e => e.IdStock)
                .HasName("PK__Stock__3A39590AA8FC8AD1");

            entity.Property(e => e.IdStock).HasColumnName("id_stock");

            entity.Property(e => e.CantidadActual).HasColumnName("cantidad_actual");

            entity.Property(e => e.PuntoMaximo).HasColumnName("punto_maximo");

            entity.Property(e => e.PuntoMinimo).HasColumnName("punto_minimo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Stock> entity);
    }
}
