// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace Data.Context.Configurations
{
    public partial class TipoBeneficioConfiguration : IEntityTypeConfiguration<TipoBeneficio>
    {
        public void Configure(EntityTypeBuilder<TipoBeneficio> entity)
        {
            entity.HasKey(e => e.IdTipoBeneficio)
                .HasName("PK__TipoBene__CFE5FB24E0BD038B");

            entity.Property(e => e.IdTipoBeneficio).HasColumnName("id_tipo_beneficio");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("descripcion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TipoBeneficio> entity);
    }
}
