// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class Acciones
    {
        public Acciones()
        {
            AccionxRol = new HashSet<AccionxRol>();
        }

        public int IdAccion { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<AccionxRol> AccionxRol { get; set; }
    }
}