// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class AccionxRol
    {
        public int IdAccion { get; set; }
        public int IdRol { get; set; }

        public virtual Acciones IdAccionNavigation { get; set; }
        public virtual Rol IdRolNavigation { get; set; }
    }
}