// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class BeneficioxSubcategoria
    {
        public int IdBeneficio { get; set; }
        public int IdSubcategoria { get; set; }

        public virtual Beneficio IdBeneficioNavigation { get; set; }
        public virtual Subcategoria IdSubcategoriaNavigation { get; set; }
    }
}