// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class Beneficio
    {
        public Beneficio()
        {
            BeneficioxProducto = new HashSet<BeneficioxProducto>();
            BeneficioxSubcategoria = new HashSet<BeneficioxSubcategoria>();
        }

        public int IdBeneficio { get; set; }
        public string Descripcion { get; set; }
        public DateTime FechaVencimiento { get; set; }
        public int? IdTipoBeneficio { get; set; }

        public virtual TipoBeneficio IdTipoBeneficioNavigation { get; set; }
        public virtual ICollection<BeneficioxProducto> BeneficioxProducto { get; set; }
        public virtual ICollection<BeneficioxSubcategoria> BeneficioxSubcategoria { get; set; }
    }
}