// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class Estados
    {
        public Estados()
        {
            Rol = new HashSet<Rol>();
            Usuario = new HashSet<Usuario>();
        }

        public int IdEstado { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<Rol> Rol { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}