// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class Producto
    {
        public Producto()
        {
            BeneficioxProducto = new HashSet<BeneficioxProducto>();
            Carrito = new HashSet<Carrito>();
            LineaDeVenta = new HashSet<LineaDeVenta>();
        }

        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public decimal Precio { get; set; }
        public string Especificacion { get; set; }
        public int IdStock { get; set; }
        public int IdSubcategoria { get; set; }

        public virtual Stock IdStockNavigation { get; set; }
        public virtual Subcategoria IdSubcategoriaNavigation { get; set; }
        public virtual ICollection<BeneficioxProducto> BeneficioxProducto { get; set; }
        public virtual ICollection<Carrito> Carrito { get; set; }
        public virtual ICollection<LineaDeVenta> LineaDeVenta { get; set; }
    }
}