// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class Rol
    {
        public Rol()
        {
            AccionxRol = new HashSet<AccionxRol>();
            RolxUsuario = new HashSet<RolxUsuario>();
        }

        public int IdRol { get; set; }
        public int EstadoRol { get; set; }
        public string Descripcion { get; set; }

        public virtual Estados EstadoRolNavigation { get; set; }
        public virtual ICollection<AccionxRol> AccionxRol { get; set; }
        public virtual ICollection<RolxUsuario> RolxUsuario { get; set; }
    }
}