// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class Subcategoria
    {
        public Subcategoria()
        {
            BeneficioxSubcategoria = new HashSet<BeneficioxSubcategoria>();
            Producto = new HashSet<Producto>();
        }

        public int IdSubcategoria { get; set; }
        public string Descripcion { get; set; }
        public int IdCategoria { get; set; }

        public virtual Categoria IdCategoriaNavigation { get; set; }
        public virtual ICollection<BeneficioxSubcategoria> BeneficioxSubcategoria { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
    }
}