// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class Test
    {
        public int Id { get; set; }
        public string Prueba { get; set; }
    }
}