// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class TipoBeneficio
    {
        public TipoBeneficio()
        {
            Beneficio = new HashSet<Beneficio>();
        }

        public int IdTipoBeneficio { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<Beneficio> Beneficio { get; set; }
    }
}