// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class Usuario
    {
        public Usuario()
        {
            RolxUsuario = new HashSet<RolxUsuario>();
            Venta = new HashSet<Venta>();
        }

        public int IdUsuario { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public int EstadoUsuario { get; set; }
        public string Contraseña { get; set; }
        public int Cuit { get; set; }
        public int Telefono { get; set; }

        public virtual Estados EstadoUsuarioNavigation { get; set; }
        public virtual ICollection<RolxUsuario> RolxUsuario { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}