// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Data.Context
{
    public partial class Venta
    {
        public Venta()
        {
            LineaDeVenta = new HashSet<LineaDeVenta>();
        }

        public int IdVenta { get; set; }
        public int? IdUsuario { get; set; }
        public int? IdCliente { get; set; }
        public decimal? Total { get; set; }

        public virtual Cliente IdClienteNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<LineaDeVenta> LineaDeVenta { get; set; }
    }
}