// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Context.Configurations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Data.Context
{
    public partial class ECommerceContext : DbContext
    {
        public ECommerceContext()
        {
        }

        public ECommerceContext(DbContextOptions<ECommerceContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Acciones> Acciones { get; set; }
        public virtual DbSet<AccionxRol> AccionxRol { get; set; }
        public virtual DbSet<Beneficio> Beneficio { get; set; }
        public virtual DbSet<BeneficioxProducto> BeneficioxProducto { get; set; }
        public virtual DbSet<BeneficioxSubcategoria> BeneficioxSubcategoria { get; set; }
        public virtual DbSet<Carrito> Carrito { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<LineaDeVenta> LineaDeVenta { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolxUsuario> RolxUsuario { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Subcategoria> Subcategoria { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TipoBeneficio> TipoBeneficio { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.AccionesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AccionxRolConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.BeneficioConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.BeneficioxProductoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.BeneficioxSubcategoriaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CarritoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CategoriaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ClienteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EstadosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.LineaDeVentaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RolConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RolxUsuarioConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.StockConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SubcategoriaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TestConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TipoBeneficioConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UsuarioConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VentaConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
